"""Export a reference fixture so other languages can recompute MASE.

The dataset this project measures is a 711 MB download that is not in the
repository, so reports/*.json cannot be regenerated by a checkout and there is
no per-series file underneath them to recompute the medians from. What CAN be
pinned down is the thing every published number is made of: the MASE definition
itself, and the rolling-origin index arithmetic in src/fb/harness.py.

This writes five files under verify/fixture/, all from the repository's own
harness:

  history.csv    ten deterministic series, series,t,y
  forecasts.csv  what harness.seasonal_naive and harness.daily_naive predicted
                 at every origin, series,model,origin,step,yhat
  folds.csv      the mean absolute error the harness scored at each origin,
                 series,model,origin,mae
  expected.csv   the MASE it divided those by, and the denominator it used
  summary.csv    the median/mean/beats aggregation src/fb/models.py applies

The other implementations under verify/ read history.csv and forecasts.csv and
rebuild folds.csv, expected.csv and summary.csv from the definition of MASE.
They never read the Python. Everything is written at full double precision, so
"agreement to 1e-12" is a statement about arithmetic and not about rounding.
Regenerating is deterministic: the same bytes on any machine.

    python verify/make_fixture.py

The fixture is committed. CI checks it, it does not rebuild it, because rebuilding
it needs numpy and checking it must not.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src" / "fb"))

import harness  # noqa: E402

OUT = Path(__file__).resolve().parent / "fixture"
SEASON = 168
HORIZON = 24
N_ORIGINS = 10
N_SERIES = 10
MODELS = ("seasonal_naive", "daily_naive")


def make_series(i: int) -> np.ndarray:
    """One deterministic series, hourly, with daily and weekly seasonality.

    Levels span 1000x across the ten series, because the real meters span
    5,332x and a metric that is fine at one scale can still lose precision at
    another. Values are rounded to six decimals so the CSV round-trips exactly.
    """
    n = 3000 + 72 * i
    level = 20.0 * (1000.0 ** (i / (N_SERIES - 1)))
    t = np.arange(n, dtype=float)
    phase = 0.3 * i
    y = level * (1.0
                 + 0.40 * np.sin(2 * np.pi * t / 24 + phase)
                 + 0.20 * np.sin(2 * np.pi * t / 168)
                 + 0.08 * np.random.default_rng(i).normal(0.0, 1.0, n))
    return np.round(y, 6)


def recording(fn, seen: list[tuple[int, np.ndarray]]):
    def wrapped(history: np.ndarray, horizon: int) -> np.ndarray:
        pred = np.asarray(fn(history, horizon), dtype=float)
        seen.append((len(history), pred))
        return pred
    return wrapped


def main() -> None:
    OUT.mkdir(exist_ok=True)
    hist_lines = ["series,t,y"]
    fc_lines = ["series,model,origin,step,yhat"]
    fold_lines = ["series,model,origin,mae"]
    series_meta = []
    per_series = []

    for i in range(N_SERIES):
        name = f"s{i}"
        y = make_series(i)
        for t, v in enumerate(y):
            hist_lines.append(f"{name},{t},{v:.6f}")

        for model in MODELS:
            fn = getattr(harness, model)
            seen: list[tuple[int, np.ndarray]] = []
            r = harness.rolling_backtest(y, recording(fn, seen),
                                         horizon=HORIZON, n_origins=N_ORIGINS,
                                         season=SEASON)
            assert r.status == "ok", (name, model, r.reasons)
            assert len(seen) == len(r.per_origin) == N_ORIGINS
            for (origin, pred), mae in zip(seen, r.per_origin):
                for step, v in enumerate(pred):
                    fc_lines.append(f"{name},{model},{origin},{step},{v:.6f}")
                fold_lines.append(f"{name},{model},{origin},{mae!r}")
            per_series.append({"series": name, "model": model, "mase": r.mase})
            if model == MODELS[0]:
                series_meta.append({
                    "series": name, "n": int(len(y)),
                    "first_origin": int(r.diagnostics["first_origin_index"]),
                    "mase_denominator": r.diagnostics["mase_denominator"]})

    (OUT / "history.csv").write_text("\n".join(hist_lines) + "\n")
    (OUT / "forecasts.csv").write_text("\n".join(fc_lines) + "\n")
    (OUT / "folds.csv").write_text("\n".join(fold_lines) + "\n")

    # the CSV must round-trip exactly, otherwise "agreement to 1e-12" would be
    # measuring the printf format rather than the arithmetic
    check = np.loadtxt(OUT / "history.csv", delimiter=",", skiprows=1,
                       usecols=2, dtype=float)
    rebuilt = np.concatenate([make_series(i) for i in range(N_SERIES)])
    assert np.array_equal(check, rebuilt), "history.csv does not round-trip"

    meta = {m["series"]: m for m in series_meta}
    exp_lines = ["series,model,n,first_origin,mase_denominator,mase"]
    for p in per_series:
        m = meta[p["series"]]
        exp_lines.append(
            f"{p['series']},{p['model']},{m['n']},{m['first_origin']},"
            f"{m['mase_denominator']!r},{p['mase']!r}")
    (OUT / "expected.csv").write_text("\n".join(exp_lines) + "\n")

    # the same aggregation src/fb/models.py and src/fb/backtest.py apply to real
    # series: median and mean across series, and the fraction of series scoring
    # below 1, which is the fraction that beat the seasonal naive
    sum_lines = ["model,series,mase_median,mase_mean,beats_naive_frac"]
    for model in MODELS:
        v = np.array([p["mase"] for p in per_series if p["model"] == model])
        sum_lines.append(f"{model},{len(v)},{float(np.median(v))!r},"
                         f"{float(np.mean(v))!r},{float(np.mean(v < 1))!r}")
    (OUT / "summary.csv").write_text("\n".join(sum_lines) + "\n")

    for p in per_series:
        print(f"  {p['series']:4} {p['model']:16} MASE {p['mase']:.6f}")
    print(f"\nwrote {len(hist_lines) - 1} history rows, "
          f"{len(fc_lines) - 1} forecast rows, {len(fold_lines) - 1} folds")


if __name__ == "__main__":
    main()
